/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-17 16:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>welcome Food Tech</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("    margin: 0%;\r\n");
      out.write("    padding: 0%;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    /* background-image: url(\"https://media.istockphoto.com/id/184103864/photo/clouds-on-sky.jpg?s=612x612&w=0&k=20&c=3JGI13B8xwZIObLtl8IN1VFtPErHv2pKiWV0tTuemsI=\"); */\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-attachment:fixed;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    padding: 40px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("body div{\r\n");
      out.write("    /* border: 2px solid red; */\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    width: 800px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left:100px;\r\n");
      out.write("    top: 100px;\r\n");
      out.write("}\r\n");
      out.write(" #d3{\r\n");
      out.write("  border-radius:20px;\r\n");
      out.write(" box-shadow: 5px 5px 20px black;\r\n");
      out.write("    background-image: url(\"https://media.istockphoto.com/id/996182206/photo/assorted-indian-food-for-lunch-or-dinner-rice-lentils-paneer-dal-makhani-naan-chutney-spices.jpg?s=612x612&w=0&k=20&c=I6Nlb95_dMC9tpl6FsbjLQBT23LjyS3CmBBLQe5yLRM=\");\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-size: inherit;\r\n");
      out.write("    width: 95%;\r\n");
      out.write("    height: 600px;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    left: 30px;\r\n");
      out.write("    top: 90px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" img{\r\n");
      out.write(" width:500px;\r\n");
      out.write(" height:500px;\r\n");
      out.write(" box-shadow: 5px 5px 20px black;\r\n");
      out.write("  border-radius: 100%;\r\n");
      out.write(" }\r\n");
      out.write("#d1{\r\n");
      out.write("\r\n");
      out.write(" background-color:Ivory;\r\n");
      out.write(" border-radius:100%;\r\n");
      out.write(" box-shadow:5px 5px 30px black;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 480px;\r\n");
      out.write("    color: bisque;\r\n");
      out.write("     /* background-image: url(\"https://media.istockphoto.com/id/953140058/photo/cooking-nd-seasoning-spices-border-on-black-slate-background.jpg?s=612x612&w=0&k=20&c=O6qm_B41xGdtAjzoqvA4pyHGqg8p7ZOgwnPZMMKzPU4=\");  */\r\n");
      out.write("     background-repeat: no-repeat;\r\n");
      out.write("     background-size: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  #d2{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    left: 660px;\r\n");
      out.write("    bottom: 30px;\r\n");
      out.write("    width: 500px;\r\n");
      out.write("    /* background-image: url(\"https://media.istockphoto.com/id/1297483389/photo/masala-tea-chai.jpg?s=612x612&w=0&k=20&c=Pv-QROSSywNh_qzHIIjHJeJB7OT0ujrKQsSiTgOmJAs=\");  */\r\n");
      out.write("  } \r\n");
      out.write("  #w1{\r\n");
      out.write("    margin-left:500px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 280px;\r\n");
      out.write("    word-spacing: 5px;\r\n");
      out.write("     font-size: 50px;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("   text-shadow:5px 5px 5px white;\r\n");
      out.write("color:black;\r\n");
      out.write("    text-indent: initial;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #w2{\r\n");
      out.write("  margin-left:400px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    bottom: 230px;\r\n");
      out.write("    word-spacing: 5px;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    text-shadow:3px 3px 10px white;\r\n");
      out.write("color:black;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  #a1{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 100px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    font-weight: 550;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    background-color:coral;\r\n");
      out.write("    box-shadow: 15px 8px 6px rgb(24, 1, 1);\r\n");
      out.write("  }\r\n");
      out.write("  #a2{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 80px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    font-weight: 550;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    background-color: coral;\r\n");
      out.write("    box-shadow: 15px 8px 6px rgb(24, 1, 1);\r\n");
      out.write("  }\r\n");
      out.write("  a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("   text-shadow: 4px 4px 10px white;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("  }\r\n");
      out.write("   button{\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"d3\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"d1\">\r\n");
      out.write("        \r\n");
      out.write("        <img alt=\"\" src=\"https://st4.depositphotos.com/5040187/19758/v/450/depositphotos_197589224-stock-illustration-logo-swoosh-global-red-letter.jpg\">\r\n");
      out.write("        \r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("    <br>\r\n");
      out.write("    <div id=\"d2\">\r\n");
      out.write("    \r\n");
      out.write("        <button id=\"a1\"><a href=\"login.jsp\">User</a></button>\r\n");
      out.write("        <button id=\"a2\"><a href=\"managerLogin.jsp\">HOTEL MANAGER</a></button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("    <h1 id=\"w1\">WELCOME  TO </h1>\r\n");
      out.write("        <h1  id=\"w2\">FOOD TECH</h1>\r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
