/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-17 20:36:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>User Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("margin:0%;\r\n");
      out.write("padding:0%;\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("}\r\n");
      out.write("main div:first-child,section{\r\n");
      out.write("box-shadow:5px 5px 30px black;\r\n");
      out.write("border-radius:20px;\r\n");
      out.write("width: 500px;\r\n");
      out.write("height: 500px;\r\n");
      out.write("}\r\n");
      out.write("section{\r\n");
      out.write("padding: 50px;\r\n");
      out.write("background-color: white;\r\n");
      out.write("}\r\n");
      out.write("main{\r\n");
      out.write("\r\n");
      out.write("background-image: url(\"https://th.bing.com/th/id/OIP.21HAWGFM1TJhxFlB-7l0zgHaEo?rs=1&pid=ImgDetMain\");\r\n");
      out.write("background-size:cover;\r\n");
      out.write("height:800px;\r\n");
      out.write(" display: flex;\r\n");
      out.write(" justify-content: center;\r\n");
      out.write(" align-items:center;\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("margin:20px;\r\n");
      out.write("margin-left:40px;\r\n");
      out.write("width:400px;\r\n");
      out.write("border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form{\r\n");
      out.write("padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1,h3{\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: xx-large;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("padding: 10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("width:200px;\r\n");
      out.write("padding:10px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" section button {\r\n");
      out.write("	margin-left: 150px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	font-size: x-large;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-weight: 100px;\r\n");
      out.write("	background-color: brown;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("margin-top:10px;\r\n");
      out.write("	margin-left: 80px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("input{\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-family: serif;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    font-size: medium;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main div:first-child{\r\n");
      out.write("background: url(\"https://images.pexels.com/photos/281260/pexels-photo-281260.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1\");}\r\n");
      out.write("\r\n");
      out.write("main div:first-child h1{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("width:400px;\r\n");
      out.write("margin-left:40px;\r\n");
      out.write("text-align:center;\r\n");
      out.write("box-shadow:5px 5px 30px black;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("main div:first-child button a{\r\n");
      out.write("margin: 50px;\r\n");
      out.write("padding: 0%;\r\n");
      out.write(" width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-weight: 100px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("main div:first-child button{\r\n");
      out.write("background-color: brown;\r\n");
      out.write("border-radius: 10px;\r\n");
      out.write("margin:20px;\r\n");
      out.write("margin-left: 150px;\r\n");
      out.write("box-shadow:5px 5px 30px white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("label,a{\r\n");
      out.write("    \r\n");
      out.write("    font-family: serif;\r\n");
      out.write("    font-size: x-large;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div>\r\n");
      out.write("		<img alt=\"\" src=\"https://st4.depositphotos.com/5040187/19758/v/450/depositphotos_197589224-stock-illustration-logo-swoosh-global-red-letter.jpg\">\r\n");
      out.write("			 <h1>Welcome to Food Tech</h1>\r\n");
      out.write("			 <button id=\"home\"><a href=\"home.jsp\">Home</a></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<section>\r\n");
      out.write("			");

			String msg = (String) request.getAttribute("msg");
			if (msg != null) {
			
      out.write("\r\n");
      out.write("			<h1>");
      out.print(msg);
      out.write("</h1>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("			<form action=\"login\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("				<h1 style=\"color: blue;\"></h1>\r\n");
      out.write("\r\n");
      out.write("				<h3 id=\"login\">LOGIN</h3>\r\n");
      out.write("				<div id=\"hm\">\r\n");
      out.write("					\r\n");
      out.write("					<table>\r\n");
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><label for=\"n\">Email:</label></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"email\" id=\"n\"\r\n");
      out.write("								placeholder=\"Enter your Email\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><label for=\"m\">Password:</label></td>\r\n");
      out.write("							<td><input type=\"text\" name=\"pwd\" id=\"m\"\r\n");
      out.write("								placeholder=\"Enter your Password\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<br> \r\n");
      out.write("				<button id=\"b1\">Submit</button><br>\r\n");
      out.write("					<br> \r\n");
      out.write("						<br> \r\n");
      out.write("				\r\n");
      out.write("				<a href=\"register.jsp\">Create A New User</a>\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
