/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-17 18:57:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class managerLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Manager Login</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("    background-color: antiquewhite;\r\n");
      out.write("    background-image: url(\"https://media.istockphoto.com/id/1129661826/photo/wood-texture-table-top-with-blur-light-gold-bokeh-in-cafe-restaurant-background-for-montage.jpg?s=612x612&w=0&k=20&c=9k3Tz9a-5M-g9Xsqr4NyIfqVnhr-JXgOIpaRfzN30us=\");\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("div{\r\n");
      out.write("    /* border: 2px solid; */\r\n");
      out.write("    margin-left: 33%;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("    font-size: xx-large;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("     text-shadow: 3px 3px 5px white;\r\n");
      out.write("    text-shadow: 8px,6px,3px;\r\n");
      out.write("    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    border-color: beige;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-size: medium;\r\n");
      out.write("    /* font-style: normal; */\r\n");
      out.write("    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    margin-left: 15px;\r\n");
      out.write("    box-shadow: 4px 4px 5px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#d1{\r\n");
      out.write("    margin-left: 200px;\r\n");
      out.write("    top: 10px;\r\n");
      out.write("}\r\n");
      out.write("#d1 button{\r\n");
      out.write("    /* color: red; */\r\n");
      out.write("    margin-top: -90px;\r\n");
      out.write("    border: 10px;\r\n");
      out.write("    background-color: rgb(225, 18, 18);\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 3px 3px 5px black;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-size: x-large;\r\n");
      out.write("}\r\n");
      out.write("#d1 a{\r\n");
      out.write("    text-shadow: 4px 4px 5px rgb(102, 190, 90);\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-size: x-large;\r\n");
      out.write("    /* margin-right: 100px; */\r\n");
      out.write("    margin-left: -100px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-family: 'Times New Roman', Times, serif;\r\n");
      out.write("    color:white;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("    color: aliceblue;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    text-shadow: 3px 3px 5px blue;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("#home{\r\n");
      out.write("   position:fixed;\r\n");
      out.write("   top: 2%;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    box-shadow: 3px 3px 5px black;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    font-size: x-large;\r\n");
      out.write("   border-radius: 10px;\r\n");
      out.write("   background-color: rgb(225, 18, 18);\r\n");
      out.write("}\r\n");
      out.write("#home a{\r\n");
      out.write("    \r\n");
      out.write("    color:black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
 String msg=(String)request.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<h1 style=\"color:white;\">");
      out.print(msg);
      out.write("</h1>\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button id=\"home\"><a href=\"home.jsp\">Home</a></button>\r\n");
      out.write("<form action=\"managerlogin\" method=\"post\">\r\n");
      out.write("<h1>LOGIN MANAGER</h1>\r\n");
      out.write("      <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"n\">Email:</label></td>\r\n");
      out.write("                <td><input type=\"text\" name=\"email\" id=\"n\" placeholder=\"Enter your Email\"></td> \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr> \r\n");
      out.write("                <td><label for=\"m\">Password:</label></td>\r\n");
      out.write("                <td><input type=\"text\" name=\"pwd\" id=\"m\" placeholder=\"Enter your Password\"></td> \r\n");
      out.write("            </tr>\r\n");
      out.write("        </table> <br>\r\n");
      out.write("        <div id=\"d1\">\r\n");
      out.write("            <button id=\"b1\">Submit</button> <br> <br>\r\n");
      out.write("             <a href=\"manager.jsp\">Create A New User..?</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
